#!/usr/bin/env python3
"""Check GRAMMAR.md's reference production against the implementation.

    .venv/bin/python tools/check_ref_grammar.py [--help]

WHY THIS EXISTS
    GRAMMAR.md (docs/) claims its `ref` production is *complete*: every form
    `yapyon.lexer.parse_ref` accepts is generated by it, and every form it
    generates is accepted. A claim like that is indistinguishable from a false
    one unless something executes it -- which is trap 6, and it is how the
    pre-split spec came to carry a production that could not generate
    `{cfg.__AS_JSON__()}` at all.

WHAT IT DOES
    Transcribes GRAMMAR §G5's EBNF into a recursive-descent recognizer --
    literally, production by production, so the transcription can be eyeballed
    against the document -- then runs both over a combinatorial corpus of
    heads x steps x tails and reports every disagreement.

    A mismatch means one of three things, and it is worth deciding which
    before changing anything:
      impl=Y grammar=n  the document is too narrow, OR this recognizer is
      impl=n grammar=Y  the document is too wide, OR the implementation is
      ...and either document or code may be the one that is wrong.

    It also checks the one thing the corpus cannot: that the document's
    `serializer` production lists exactly the names `SERIALIZER_NAMES` holds.
    The corpus compares *shapes*, so a serializer present in the code and
    absent from the document would simply never be generated and never be
    tested. That check is a direct document-against-code comparison.

WHY THE TRANSCRIPTION DOES NOT IMPORT THE IMPLEMENTATION
    The recognizer below deliberately re-states the document's rules --
    `is_dunder`, the SEG constraint, the shape of each production -- instead
    of importing `yapyon.lexer`'s versions. Importing them would compare the
    implementation against itself and the whole check would pass vacuously.
    The terminals of the `serializer` production are read from GRAMMAR.md for
    the same reason: this recognizer speaks for the *document*, and the
    document is the thing on trial.

WHEN TO RUN IT
    After any change to lexer.parse_ref, and after any edit to GRAMMAR §G5.
    `tests/test_ref_grammar.py` also runs it, so the suite covers it.
"""
import itertools, re, sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(_ROOT / "src"))
from yapyon.lexer import parse_ref, RefError
from yapyon.serializers import SERIALIZER_NAMES

GRAMMAR = _ROOT / "docs" / "GRAMMAR.md"


def serializers_from_grammar(path=GRAMMAR):
    """The names GRAMMAR §G5's `serializer` production actually lists.

    Read from the document rather than hardcoded, so this recognizer cannot
    quietly disagree with the text it claims to transcribe.
    """
    names, started = [], False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not started:
            m = re.match(r"^serializer\s*::=\s*(.*)$", line)
            if not m:
                continue
            started, rest = True, m.group(1)
        elif line.startswith("|"):
            rest = line[1:]
        else:
            break
        names.extend(re.findall(r'"(__[A-Za-z0-9_]+__)"', rest))
    if not started:
        raise SystemExit(f"no `serializer ::=` production found in {path}")
    return tuple(names)


SERIALIZERS = serializers_from_grammar()
KEYWORDS = ("True", "False", "None")
TOK = re.compile(r'''\s*(?:(?P<str>"[^"]*"|'[^']*')|(?P<int>[+-]?\d+)|(?P<name>[^\s.\[\]()]+)|(?P<p>[.\[\]()]))''')

def lex(s):
    out, i = [], 0
    while i < len(s):
        m = TOK.match(s, i)
        if not m or m.end() == i: return None
        i = m.end()
        for k in ("str", "int", "name", "p"):
            if m.group(k) is not None:
                out.append((k, m.group(k))); break
    return out

def is_dunder(n): return n.startswith("__") and n.endswith("__") and len(n) >= 2
def is_name(n): return n.isidentifier() and n not in KEYWORDS
def is_seg(n): return is_name(n) and not is_dunder(n)

class P:
    def __init__(self, toks): self.t, self.i = toks, 0
    def peek(self, k=0): return self.t[self.i+k] if self.i+k < len(self.t) else (None, None)
    def take(self): v = self.peek(); self.i += 1; return v
    def at(self, kind, val=None):
        k, v = self.peek()
        return k == kind and (val is None or v == val)

    # ref ::= key_ref | value_ref
    def ref(self):
        save = self.i
        if self.key_ref() and self.i == len(self.t): return True
        self.i = save
        return self.value_ref()

    # key_ref ::= parents "." "__KEY__" | "__KEY__"
    def key_ref(self):
        if self.at("name", "__KEY__"): self.take(); return True
        if not self.parents(): return False
        if not self.at("p", "."): return False
        self.take()
        if not self.at("name", "__KEY__"): return False
        self.take(); return True

    # parents ::= "__PARENT__" ("." "__PARENT__")*
    def parents(self):
        if not self.at("name", "__PARENT__"): return False
        self.take()
        while self.at("p", ".") and self.peek(1) == ("name", "__PARENT__"):
            self.take(); self.take()
        return True

    # anchor ::= "__ROOT__" | parents
    def anchor(self):
        if self.at("name", "__ROOT__"): self.take(); return True
        return self.parents()

    # step ::= "." SEG | subscript
    def step(self):
        if self.at("p", ".") and self.peek(1)[0] == "name" and is_seg(self.peek(1)[1]):
            self.take(); self.take(); return True
        return self.subscript()

    def subscript(self):
        if not self.at("p", "["): return False
        self.take()
        if not self.sub(): return False
        if not self.at("p", "]"): return False
        self.take(); return True

    # sub ::= STRING | INDEX | ref
    def sub(self):
        if self.at("str"): self.take(); return True
        if self.at("int"):
            v = self.peek()[1]
            if v.lstrip("+-") != v: return False      # INDEX is unsigned
            self.take(); return True
        depth, j = 0, self.i
        while j < len(self.t):
            k, v = self.t[j]
            if k == "p" and v == "[": depth += 1
            elif k == "p" and v == "]":
                if depth == 0: break
                depth -= 1
            j += 1
        inner = P(self.t[self.i:j])
        if inner.ref() and inner.i == len(inner.t):
            self.i = j; return True
        return False

    def serializer(self):
        k, v = self.peek()
        if k != "name" or v not in SERIALIZERS: return False
        if self.peek(1) != ("p", "(") or self.peek(2) != ("p", ")"): return False
        self.take(); self.take(); self.take(); return True

    # value_ref ::= path | serialized
    def value_ref(self):
        save = self.i
        if self.serialized() and self.i == len(self.t): return True
        self.i = save
        return self.path() and self.i == len(self.t)

    # path ::= (anchor | SEG) step*
    def path(self):
        if not self.head(): return False
        while self.step(): pass
        return True

    def head(self):
        save = self.i
        if self.anchor(): return True
        self.i = save
        if self.peek()[0] == "name" and is_seg(self.peek()[1]):
            self.take(); return True
        return False

    # serialized ::= anchor step+ "." serializer | SEG step* "." serializer
    def serialized(self):
        save = self.i
        if self.anchor():
            if not self.step(): self.i = save
            else:
                while self.step(): pass
                return self.dot_ser()
        self.i = save
        if self.peek()[0] == "name" and is_seg(self.peek()[1]):
            self.take()
            while self.step(): pass
            return self.dot_ser()
        return False

    def dot_ser(self):
        if not self.at("p", "."): return False
        self.take()
        return self.serializer()

def generates(s):
    toks = lex(s)
    if toks is None or not toks: return False
    p = P(toks)
    return p.ref() and p.i == len(p.t)

heads = ["a", "__ROOT__", "__PARENT__", "__PARENT__.__PARENT__", "__foo__",
         "True", "0", "__", "___", "_a", "a1"]
steps = ["", ".b", "[0]", "[-1]", '["b.c"]', "[p]", ".b[0]", "[p].c",
         ".__KEY__", ".__PARENT__", "[a[b]]", "..b", ".0", ".True", "[__KEY__]"]
# Derived from the code, not listed by hand: a serializer the implementation
# gains must be exercised here without anyone remembering to add it. The two
# negatives stay fixed -- an unknown name, and a call on no name at all.
tails = [""] + [f".{n}()" for n in SERIALIZER_NAMES] + [".__AS_BOGUS__()", ".__KEY__", "()"]


def mismatches():
    """Every corpus form the document and the implementation disagree about."""
    out = []
    for h, s, t in itertools.product(heads, steps, tails):
        c = h + s + t
        try:
            parse_ref(c); impl = True
        except Exception: impl = False
        try: doc = generates(c)
        except Exception: doc = False
        if impl != doc:
            out.append((c, impl, doc))
    return len(heads) * len(steps) * len(tails), out


def main():
    doc, code = set(SERIALIZERS), set(SERIALIZER_NAMES)
    if doc != code:
        print(f"  SERIALIZER MISMATCH  {GRAMMAR.name} lists {sorted(doc)}, "
              f"SERIALIZER_NAMES holds {sorted(code)}")
        if doc - code: print(f"    only in the document: {sorted(doc - code)}")
        if code - doc: print(f"    only in the code:     {sorted(code - doc)}")
        return 1
    n, bad = mismatches()
    for c, impl, d in bad[:15]:
        print(f"  MISMATCH {c!r:44} impl={'Y' if impl else 'n'} grammar={'Y' if d else 'n'}")
    print(f"\n{n} forms checked, {len(bad)} mismatches; "
          f"serializer production agrees with SERIALIZER_NAMES ({len(code)} names)")
    return 1 if bad else 0


if __name__ == "__main__":
    # Checked here rather than at import: `pytest -h` would otherwise exit
    # during collection, because tests/test_ref_grammar.py imports this module.
    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__); raise SystemExit(0)
    raise SystemExit(main())
