"""Generate src/yapyon/_xid.py, the pinned identifier table (GRAMMAR §G4.1).

Usage:
    .venv/bin/python tools/gen_xid_table.py [DerivedCoreProperties.txt]

With no argument, fetches the file for the pinned version from unicode.org.
The table is XID_Start and XID_Continue, each minus Default_Ignorable_Code_Point,
as sorted inclusive ranges, plus the default-ignorables that were removed from
them (so a diagnostic can say "invisible" rather than "unexpected").
Changing the pin means changing UNICODE_VERSION below, re-running this, and
reviewing the diff -- it is a change to the format, not a refresh.
"""

import sys
import urllib.request
from pathlib import Path

UNICODE_VERSION = "14.0.0"
URL = f"https://www.unicode.org/Public/{UNICODE_VERSION}/ucd/DerivedCoreProperties.txt"
OUT = Path(__file__).resolve().parent.parent / "src" / "yapyon" / "_xid.py"


def load(text: str, prop: str) -> set[int]:
    out = set()
    for line in text.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        rng, name = (f.strip() for f in line.split(";")[:2])
        if name != prop:
            continue
        lo, _, hi = rng.partition("..")
        out.update(range(int(lo, 16), int(hi or lo, 16) + 1))
    return out


def ranges(points: set[int]) -> list[tuple[int, int]]:
    out: list[list[int]] = []
    for c in sorted(points):
        if out and c == out[-1][1] + 1:
            out[-1][1] = c
        else:
            out.append([c, c])
    return [(a, b) for a, b in out]


def render(name: str, rs: list[tuple[int, int]]) -> str:
    body = "".join(f"    (0x{a:04X}, 0x{b:04X}),\n" for a, b in rs)
    return f"{name} = (\n{body})\n"


def main(argv: list[str]) -> None:
    if len(argv) > 1 and argv[1] in ("-h", "--help"):
        print(__doc__)
        return
    if len(argv) > 1:
        text = Path(argv[1]).read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(URL) as r:
            text = r.read().decode("utf-8")
    if f"DerivedCoreProperties-{UNICODE_VERSION}.txt" not in text[:200]:
        raise SystemExit(f"not the {UNICODE_VERSION} DerivedCoreProperties file")
    ignorable = load(text, "Default_Ignorable_Code_Point")
    start = load(text, "XID_Start") - ignorable
    cont = load(text, "XID_Continue") - ignorable
    excluded = load(text, "XID_Continue") & ignorable
    OUT.write_text(
        '"""GENERATED by tools/gen_xid_table.py -- do not edit.\n\n'
        f"Unicode {UNICODE_VERSION} XID_Start and XID_Continue, each minus\n"
        "Default_Ignorable_Code_Point, as sorted inclusive ranges (GRAMMAR §G4.1).\n"
        f"{len(start)} start and {len(cont)} continue code points.\n"
        '"""\n\n'
        f'UNICODE_VERSION = "{UNICODE_VERSION}"\n\n'
        + render("XID_START", ranges(start)) + "\n"
        + render("XID_CONTINUE", ranges(cont)) + "\n"
        + "# Identifier characters removed as invisible, for diagnostics only.\n"
        + render("XID_IGNORED", ranges(excluded)),
        encoding="utf-8")
    print(f"wrote {OUT}: {len(start)} start, {len(cont)} continue")


if __name__ == "__main__":
    main(sys.argv)
